/**
 * This is an autogenerated netlist code from CircuitVerse. Verilog Code can be
 * tested on https://www.edaplayground.com/ using Icarus Verilog 0.9.7. This is an
 * experimental module and some manual changes make need to be done in order for
 * this to work.
 *
 * If you have any ideas/suggestions or bug fixes, raise an issue
 * on https://github.com/CircuitVerse/CircuitVerse/issues/new/choose
 */

/*
  Element Usage Report
    Input - 26 times
    XorGate - 4 times
    Output - 14 times
    AndGate - 6 times
    OrGate - 4 times
    Multiplexer - 7 times
    SubCircuit - 7 times
    NotGate - 4 times
    Splitter - 5 times
    NorGate - 1 times
    Ground - 3 times
*/

/*
  Usage Instructions and Tips
    Labels - Ensure unique label names and avoid using verilog keywords
    Warnings - Connect all optional inputs to remove warnings
*/

// Sample Testbench Code - Uncomment to use

/*
module TestBench();

  reg A, B, a, b, CarryIn;
  reg [1:0] Operation;
  reg [3:0] ALU_operation, b, a;

  wire Carry, Sum, Result, CarryOut, Overflow, Zero;
  wire [3:0] Result;

  half_adder DUT0(Carry, Sum, A, B);

  ALU_1bit_v0 DUT1(Result, CarryOut, a, b, CarryIn, Operation);

  ALU_4bit DUT2(Overflow, Result, Zero, ALU_operation, b, a);

  initial begin
    A = 0;
    B = 0;
    a = 0;
    b = 0;
    CarryIn = 0;
    Operation = 0;
    ALU_operation = 0;

    #15
    $display("Carry = %b", Carry);
    $display("Sum = %b", Sum);
    $display("Result = %b", Result);
    $display("CarryOut = %b", CarryOut);
    $display("Overflow = %b", Overflow);
    $display("Zero = %b", Zero);

    #10
    $display("Carry = %b", Carry);
    $display("Sum = %b", Sum);
    $display("Result = %b", Result);
    $display("CarryOut = %b", CarryOut);
    $display("Overflow = %b", Overflow);
    $display("Zero = %b", Zero);

    $finish;

  end
endmodule

*/

module half_adder(Carry, Sum, A, B);
  output Carry,  Sum;
  input A, B;
  wire xor_0_out, and_0_out;
  assign xor_0_out = A ^ B;
  assign Sum = xor_0_out;
  assign and_0_out = B & A;
  assign Carry = and_0_out;
endmodule

module full_adder(Sum, CarryOut, CarryIn, a, b);
  output Sum,  CarryOut;
  input CarryIn, a, b;
  wire and_0_out, or_0_out, xor_0_out, and_1_out, xor_1_out;
  assign and_0_out = a & b;
  assign or_0_out = and_0_out | and_1_out;
  assign CarryOut = or_0_out;
  assign xor_0_out = a ^ b;
  assign and_1_out = xor_0_out & CarryIn;
  assign xor_1_out = CarryIn ^ xor_0_out;
  assign Sum = xor_1_out;
endmodule


module ALU_1bit_v0(Result, CarryOut, a, b, CarryIn, Operation);
  output Result,  CarryOut;
  input a, b, CarryIn;
  input [1:0] Operation;
  wire Multiplexer_0_out, full_adder_0_out_0, full_adder_0_out_1, or_0_out, and_0_out;
  Multiplexer4 Multiplexer_0(
  Multiplexer_0_out,
  and_0_out,
  or_0_out,
  full_adder_0_out_0,
  1'b0,
  Operation
); 
  assign Result = Multiplexer_0_out;
  full_adder full_adder_0(full_adder_0_out_0, full_adder_0_out_1, CarryIn, a, b);
  assign CarryOut = full_adder_0_out_1;
  assign or_0_out = a | b;
  assign and_0_out = a & b;
endmodule


module ALU_1bit_v1(Result, CarryOut, a, b, CarryIn, Operation, Less, Ainvert, Binvert);
  output Result,  CarryOut;
  input a, b, CarryIn, Less, Ainvert, Binvert;
  input [1:0] Operation;
  wire Multiplexer_1_out, full_adder_0_out_0, full_adder_0_out_1, Multiplexer_2_out, or_0_out, and_0_out, Multiplexer_0_out, not_1_out, not_0_out;
  Multiplexer2 Multiplexer_1(Multiplexer_1_out, b, not_1_out, Binvert);
  full_adder full_adder_0(full_adder_0_out_0, full_adder_0_out_1, CarryIn, Multiplexer_0_out, Multiplexer_1_out);
  assign CarryOut = full_adder_0_out_1;
  Multiplexer4 Multiplexer_2(Multiplexer_2_out, and_0_out, or_0_out, full_adder_0_out_0, Less, Operation);
  assign Result = Multiplexer_2_out;
  assign or_0_out = Multiplexer_0_out | Multiplexer_1_out;
  assign and_0_out = Multiplexer_0_out & Multiplexer_1_out;
  Multiplexer2 Multiplexer_0(Multiplexer_0_out, a, not_0_out, Ainvert);
  assign not_1_out = ~b;
  assign not_0_out = ~a;
endmodule


module ALU_1bit_v2(Result, Set, Overflow, a, b, CarryIn, Operation, Less, Ainvert, Binvert);
  output Result,  Set,  Overflow;
  input a, b, CarryIn, Less, Ainvert, Binvert;
  input [1:0] Operation;
  wire Multiplexer_1_out, and_0_out, Multiplexer_2_out, full_adder_0_out_0, full_adder_0_out_1, xor_0_out, xor_1_out, Multiplexer_0_out, or_0_out, not_1_out, not_0_out;
  Multiplexer2 Multiplexer_1(Multiplexer_1_out, b, not_1_out, Binvert);
  assign and_0_out = Multiplexer_0_out & Multiplexer_1_out;
  Multiplexer4 Multiplexer_2(Multiplexer_2_out, and_0_out, or_0_out, full_adder_0_out_0, Less, Operation);
  assign Result = Multiplexer_2_out;
  full_adder full_adder_0(full_adder_0_out_0, full_adder_0_out_1, CarryIn, Multiplexer_0_out, Multiplexer_1_out);
  assign xor_0_out = CarryIn ^ full_adder_0_out_1;
  assign xor_1_out = full_adder_0_out_0 ^ xor_0_out;
  assign Set = xor_1_out;
  assign Overflow = xor_0_out;
  Multiplexer2 Multiplexer_0(Multiplexer_0_out, a, not_0_out, Ainvert);
  assign or_0_out = Multiplexer_0_out | Multiplexer_1_out;
  assign not_1_out = ~b;
  assign not_0_out = ~a;
endmodule




module ALU_4bit(Overflow, Result, Zero, ALU_operation, b, a);
  output Overflow,  Zero;
  output [3:0] Result;
  input [3:0] ALU_operation, b, a;
  wire ALU_1bit_v2_1_out_0, ALU_1bit_v2_1_out_1, ALU_1bit_v2_1_out_2, ALU_1bit_v1_0_out_0, ALU_1bit_v1_0_out_1, ALU_1bit_v1_2_out_0, ALU_1bit_v1_2_out_1, ALU_1bit_v1_3_out_0, ALU_1bit_v1_3_out_1, nor_0_out, Ground_2_out, Ground_1_out, Ground_0_out;
  wire [3:0] Splitter_3_cmb;
  
  ALU_1bit_v2 ALU_1bit_v2_1(ALU_1bit_v2_1_out_0, ALU_1bit_v2_1_out_1, ALU_1bit_v2_1_out_2, a[3], b[3], ALU_1bit_v1_3_out_1, ALU_operation[1:0], Ground_2_out, ALU_operation[3], ALU_operation[2]);
  assign Overflow = ALU_1bit_v2_1_out_2;
  ALU_1bit_v1 ALU_1bit_v1_0(ALU_1bit_v1_0_out_0, ALU_1bit_v1_0_out_1, a[0], b[0], ALU_operation[2], ALU_operation[1:0], ALU_1bit_v2_1_out_1, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_2(ALU_1bit_v1_2_out_0, ALU_1bit_v1_2_out_1, a[1], b[1], ALU_1bit_v1_0_out_1, ALU_operation[1:0], Ground_0_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_3(ALU_1bit_v1_3_out_0, ALU_1bit_v1_3_out_1, a[2], b[2], ALU_1bit_v1_2_out_1, ALU_operation[1:0], Ground_1_out, ALU_operation[3], ALU_operation[2]);
  assign Splitter_3_cmb = {ALU_1bit_v2_1_out_0,ALU_1bit_v1_3_out_0,ALU_1bit_v1_2_out_0,ALU_1bit_v1_0_out_0};
  
  assign nor_0_out = ~(Splitter_3_cmb[1] | Splitter_3_cmb[0] | Splitter_3_cmb[2] | Splitter_3_cmb[3]);
  assign Zero = nor_0_out;
  assign Result = Splitter_3_cmb;
  
  
  assign Ground_2_out = 1'b0;
  assign Ground_1_out = 1'b0;
  assign Ground_0_out = 1'b0;
endmodule

module Multiplexer4(out, in0, in1, in2, in3, sel);
  parameter WIDTH = 1;
  output reg [WIDTH-1:0] out;
  input [WIDTH-1:0] in0, in1, in2, in3;
  input [1:0] sel;
  
  always @ (*)
    case (sel)
      0 : out = in0;
      1 : out = in1;
      2 : out = in2;
      3 : out = in3;
    endcase
endmodule


module Multiplexer2(out, in0, in1, sel);
  parameter WIDTH = 1;
  output reg [WIDTH-1:0] out;
  input [WIDTH-1:0] in0, in1;
  input [0:0] sel;
  
  always @ (*)
    case (sel)
      0 : out = in0;
      1 : out = in1;
    endcase
endmodule

