/**
 * This is an autogenerated netlist code from CircuitVerse. Verilog Code can be
 * tested on https://www.edaplayground.com/ using Icarus Verilog 0.9.7. This is an
 * experimental module and some manual changes make need to be done in order for
 * this to work.
 *
 * If you have any ideas/suggestions or bug fixes, raise an issue
 * on https://github.com/CircuitVerse/CircuitVerse/issues/new/choose
 */

/*
  Element Usage Report
    Input - 26 times
    XorGate - 4 times
    Output - 14 times
    AndGate - 6 times
    OrGate - 4 times
    Multiplexer - 7 times
    SubCircuit - 7 times
    NotGate - 4 times
    Splitter - 5 times
    NorGate - 1 times
    Ground - 3 times
*/

/*
  Usage Instructions and Tips
    Labels - Ensure unique label names and avoid using verilog keywords
    Warnings - Connect all optional inputs to remove warnings
*/

// Sample Testbench Code - Uncomment to use

/*
module TestBench();

  reg A, B, a, b, CarryIn;
  reg [1:0] Operation;
  reg [3:0] ALU_operation, b, a;

  wire Carry, Sum, Result, CarryOut, Overflow, Zero;
  wire [3:0] Result;

  half_adder DUT0(Carry, Sum, A, B);

  ALU_1bit_v0 DUT1(Result, CarryOut, a, b, CarryIn, Operation);

  ALU_4bit DUT2(Overflow, Result, Zero, ALU_operation, b, a);

  initial begin
    A = 0;
    B = 0;
    a = 0;
    b = 0;
    CarryIn = 0;
    Operation = 0;
    ALU_operation = 0;

    #15
    $display("Carry = %b", Carry);
    $display("Sum = %b", Sum);
    $display("Result = %b", Result);
    $display("CarryOut = %b", CarryOut);
    $display("Overflow = %b", Overflow);
    $display("Zero = %b", Zero);

    #10
    $display("Carry = %b", Carry);
    $display("Sum = %b", Sum);
    $display("Result = %b", Result);
    $display("CarryOut = %b", CarryOut);
    $display("Overflow = %b", Overflow);
    $display("Zero = %b", Zero);

    $finish;

  end
endmodule

*/

module half_adder(Carry, Sum, A, B);
  output Carry,  Sum;
  input A, B;
  wire xor_0_out, and_0_out;
  assign xor_0_out = A ^ B;
  assign Sum = xor_0_out;
  assign and_0_out = B & A;
  assign Carry = and_0_out;
endmodule

module full_adder(Sum, CarryOut, CarryIn, a, b);
  output Sum,  CarryOut;
  input CarryIn, a, b;
  wire and_0_out, or_0_out, xor_0_out, and_1_out, xor_1_out;
  assign and_0_out = a & b;
  assign or_0_out = and_0_out | and_1_out;
  assign CarryOut = or_0_out;
  assign xor_0_out = a ^ b;
  assign and_1_out = xor_0_out & CarryIn;
  assign xor_1_out = CarryIn ^ xor_0_out;
  assign Sum = xor_1_out;
endmodule


module ALU_1bit_v0(Result, CarryOut, a, b, CarryIn, Operation);
  output Result,  CarryOut;
  input a, b, CarryIn;
  input [1:0] Operation;
  wire Multiplexer_0_out, full_adder_0_out_0, full_adder_0_out_1, or_0_out, and_0_out;
  Multiplexer4 Multiplexer_0(
  Multiplexer_0_out,
  and_0_out,
  or_0_out,
  full_adder_0_out_0,
  1'b0,
  Operation
); 
  assign Result = Multiplexer_0_out;
  full_adder full_adder_0(full_adder_0_out_0, full_adder_0_out_1, CarryIn, a, b);
  assign CarryOut = full_adder_0_out_1;
  assign or_0_out = a | b;
  assign and_0_out = a & b;
endmodule


module ALU_1bit_v1(Result, CarryOut, a, b, CarryIn, Operation, Less, Ainvert, Binvert);
  output Result,  CarryOut;
  input a, b, CarryIn, Less, Ainvert, Binvert;
  input [1:0] Operation;
  wire Multiplexer_1_out, full_adder_0_out_0, full_adder_0_out_1, Multiplexer_2_out, or_0_out, and_0_out, Multiplexer_0_out, not_1_out, not_0_out;
  Multiplexer2 Multiplexer_1(Multiplexer_1_out, b, not_1_out, Binvert);
  full_adder full_adder_0(full_adder_0_out_0, full_adder_0_out_1, CarryIn, Multiplexer_0_out, Multiplexer_1_out);
  assign CarryOut = full_adder_0_out_1;
  Multiplexer4 Multiplexer_2(Multiplexer_2_out, and_0_out, or_0_out, full_adder_0_out_0, Less, Operation);
  assign Result = Multiplexer_2_out;
  assign or_0_out = Multiplexer_0_out | Multiplexer_1_out;
  assign and_0_out = Multiplexer_0_out & Multiplexer_1_out;
  Multiplexer2 Multiplexer_0(Multiplexer_0_out, a, not_0_out, Ainvert);
  assign not_1_out = ~b;
  assign not_0_out = ~a;
endmodule


module ALU_1bit_v2(Result, Set, Overflow, a, b, CarryIn, Operation, Less, Ainvert, Binvert);
  output Result,  Set,  Overflow;
  input a, b, CarryIn, Less, Ainvert, Binvert;
  input [1:0] Operation;
  wire Multiplexer_1_out, and_0_out, Multiplexer_2_out, full_adder_0_out_0, full_adder_0_out_1, xor_0_out, xor_1_out, Multiplexer_0_out, or_0_out, not_1_out, not_0_out;
  Multiplexer2 Multiplexer_1(Multiplexer_1_out, b, not_1_out, Binvert);
  assign and_0_out = Multiplexer_0_out & Multiplexer_1_out;
  Multiplexer4 Multiplexer_2(Multiplexer_2_out, and_0_out, or_0_out, full_adder_0_out_0, Less, Operation);
  assign Result = Multiplexer_2_out;
  full_adder full_adder_0(full_adder_0_out_0, full_adder_0_out_1, CarryIn, Multiplexer_0_out, Multiplexer_1_out);
  assign xor_0_out = CarryIn ^ full_adder_0_out_1;
  assign xor_1_out = full_adder_0_out_0 ^ xor_0_out;
  assign Set = xor_1_out;
  assign Overflow = xor_0_out;
  Multiplexer2 Multiplexer_0(Multiplexer_0_out, a, not_0_out, Ainvert);
  assign or_0_out = Multiplexer_0_out | Multiplexer_1_out;
  assign not_1_out = ~b;
  assign not_0_out = ~a;
endmodule




module ALU_4bit(Overflow, Result, Zero, ALU_operation, b, a);
  output Overflow,  Zero;
  output [3:0] Result;
  input [3:0] ALU_operation, b, a;
  wire ALU_1bit_v2_1_out_0, ALU_1bit_v2_1_out_1, ALU_1bit_v2_1_out_2, ALU_1bit_v1_0_out_0, ALU_1bit_v1_0_out_1, ALU_1bit_v1_2_out_0, ALU_1bit_v1_2_out_1, ALU_1bit_v1_3_out_0, ALU_1bit_v1_3_out_1, nor_0_out, Ground_2_out, Ground_1_out, Ground_0_out;
  wire [3:0] Splitter_3_cmb;
  
  ALU_1bit_v2 ALU_1bit_v2_1(ALU_1bit_v2_1_out_0, ALU_1bit_v2_1_out_1, ALU_1bit_v2_1_out_2, a[3], b[3], ALU_1bit_v1_3_out_1, ALU_operation[1:0], Ground_2_out, ALU_operation[3], ALU_operation[2]);
  assign Overflow = ALU_1bit_v2_1_out_2;
  ALU_1bit_v1 ALU_1bit_v1_0(ALU_1bit_v1_0_out_0, ALU_1bit_v1_0_out_1, a[0], b[0], ALU_operation[2], ALU_operation[1:0], ALU_1bit_v2_1_out_1, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_2(ALU_1bit_v1_2_out_0, ALU_1bit_v1_2_out_1, a[1], b[1], ALU_1bit_v1_0_out_1, ALU_operation[1:0], Ground_0_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_3(ALU_1bit_v1_3_out_0, ALU_1bit_v1_3_out_1, a[2], b[2], ALU_1bit_v1_2_out_1, ALU_operation[1:0], Ground_1_out, ALU_operation[3], ALU_operation[2]);
  assign Splitter_3_cmb = {ALU_1bit_v2_1_out_0,ALU_1bit_v1_3_out_0,ALU_1bit_v1_2_out_0,ALU_1bit_v1_0_out_0};
  
  assign nor_0_out = ~(Splitter_3_cmb[1] | Splitter_3_cmb[0] | Splitter_3_cmb[2] | Splitter_3_cmb[3]);
  assign Zero = nor_0_out;
  assign Result = Splitter_3_cmb;
  
  
  assign Ground_2_out = 1'b0;
  assign Ground_1_out = 1'b0;
  assign Ground_0_out = 1'b0;
endmodule

module Multiplexer4(out, in0, in1, in2, in3, sel);
  parameter WIDTH = 1;
  output reg [WIDTH-1:0] out;
  input [WIDTH-1:0] in0, in1, in2, in3;
  input [1:0] sel;
  
  always @ (*)
    case (sel)
      0 : out = in0;
      1 : out = in1;
      2 : out = in2;
      3 : out = in3;
    endcase
endmodule


module Multiplexer2(out, in0, in1, sel);
  parameter WIDTH = 1;
  output reg [WIDTH-1:0] out;
  input [WIDTH-1:0] in0, in1;
  input [0:0] sel;
  
  always @ (*)
    case (sel)
      0 : out = in0;
      1 : out = in1;
    endcase
endmodule


module instruction_memory(instruction, PC, reset);
  output [31:0] instruction;
  input reset;
  input [7:0] PC;
  wire [7:0] EEPROM_3_DATA_OUT, EEPROM_2_DATA_OUT, EEPROM_1_DATA_OUT, EEPROM_0_DATA_OUT;
  wire [31:0] Splitter_0_cmb;
  EEPROM #(8) EEPROM_3(EEPROM_3_DATA_OUT, PC[7:2], , , reset, );
  assign Splitter_0_cmb = {EEPROM_0_DATA_OUT,EEPROM_1_DATA_OUT,EEPROM_2_DATA_OUT,EEPROM_3_DATA_OUT};
  assign instruction = Splitter_0_cmb;
  EEPROM #(8) EEPROM_2(EEPROM_2_DATA_OUT, PC[7:2], , , reset, );
  EEPROM #(8) EEPROM_1(EEPROM_1_DATA_OUT, PC[7:2], , , reset, );
  EEPROM #(8) EEPROM_0(EEPROM_0_DATA_OUT, PC[7:2], , , reset, );
  
endmodule


module \latch-SR (NQ, Q, S, R);
  output NQ,  Q;
  input S, R;
  wire nor_1_out, nor_0_out;
  assign nor_1_out = ~(nor_0_out | R);
  assign nor_0_out = ~(S | nor_1_out);
  assign NQ = nor_0_out;
  assign Q = nor_1_out;
endmodule


module latch_D(NQ, Q, D, C);
  output NQ,  Q;
  input D, C;
  wire and_1_out, \latch-SR_0_out_0 , \latch-SR_0_out_1 , and_0_out, not_0_out;
  assign and_1_out = C & not_0_out;
  \latch-SR  \latch-SR_0 (\latch-SR_0_out_0 , \latch-SR_0_out_1 , and_0_out, and_1_out);
  assign Q = \latch-SR_0_out_1 ;
  assign NQ = \latch-SR_0_out_0 ;
  assign and_0_out = C & D;
  assign not_0_out = ~D;
endmodule



module flipflop_D_rising(NQ, Q, C, D, reset);
  output NQ,  Q;
  input C, D, reset;
  wire nor_0_out, latch_D_0_out_0, latch_D_0_out_1, not_1_out, not_0_out, and_0_out;
  assign nor_0_out = ~(not_1_out | reset);
  assign Q = nor_0_out;
  latch_D latch_D_0(latch_D_0_out_0, latch_D_0_out_1, D, and_0_out);
  assign not_1_out = ~latch_D_0_out_1;
  assign NQ = latch_D_0_out_0;
  assign not_0_out = ~C;
  assign and_0_out = C & not_0_out;
endmodule




module \8bit-register (out, in, enable, clock, reset);
  output [7:0] out;
  input enable, clock, reset;
  input [7:0] in;
  wire flipflop_D_rising_0_out_0, flipflop_D_rising_0_out_1, flipflop_D_rising_7_out_0, flipflop_D_rising_7_out_1, flipflop_D_rising_6_out_0, flipflop_D_rising_6_out_1, flipflop_D_rising_5_out_0, flipflop_D_rising_5_out_1, flipflop_D_rising_4_out_0, flipflop_D_rising_4_out_1, flipflop_D_rising_3_out_0, flipflop_D_rising_3_out_1, flipflop_D_rising_2_out_0, flipflop_D_rising_2_out_1, flipflop_D_rising_1_out_0, flipflop_D_rising_1_out_1, and_0_out;
  wire [7:0] Splitter_1_cmb;
  flipflop_D_rising flipflop_D_rising_0(flipflop_D_rising_0_out_0, flipflop_D_rising_0_out_1, and_0_out, in[7], reset);
  assign Splitter_1_cmb = {flipflop_D_rising_0_out_1,flipflop_D_rising_7_out_1,flipflop_D_rising_6_out_1,flipflop_D_rising_5_out_1,flipflop_D_rising_4_out_1,flipflop_D_rising_3_out_1,flipflop_D_rising_2_out_1,flipflop_D_rising_1_out_1};
  assign out = Splitter_1_cmb;
  flipflop_D_rising flipflop_D_rising_7(flipflop_D_rising_7_out_0, flipflop_D_rising_7_out_1, and_0_out, in[6], reset);
  flipflop_D_rising flipflop_D_rising_6(flipflop_D_rising_6_out_0, flipflop_D_rising_6_out_1, and_0_out, in[5], reset);
  flipflop_D_rising flipflop_D_rising_5(flipflop_D_rising_5_out_0, flipflop_D_rising_5_out_1, and_0_out, in[4], reset);
  flipflop_D_rising flipflop_D_rising_4(flipflop_D_rising_4_out_0, flipflop_D_rising_4_out_1, and_0_out, in[3], reset);
  flipflop_D_rising flipflop_D_rising_3(flipflop_D_rising_3_out_0, flipflop_D_rising_3_out_1, and_0_out, in[2], reset);
  flipflop_D_rising flipflop_D_rising_2(flipflop_D_rising_2_out_0, flipflop_D_rising_2_out_1, and_0_out, in[1], reset);
  flipflop_D_rising flipflop_D_rising_1(flipflop_D_rising_1_out_0, flipflop_D_rising_1_out_1, and_0_out, in[0], reset);
  assign and_0_out = clock & enable;
  
endmodule





module \8x8_register_file (rs2_data, rs1_data, rs1, rs2, clock, RegWrite, rd, rd_data, reset);
  output [7:0] rs2_data, rs1_data;
  input clock, RegWrite, reset;
  input [4:0] rs1, rs2, rd;
  input [7:0] rd_data;
  wire Decoder_0_out_0, Decoder_0_out_1, Decoder_0_out_2, Decoder_0_out_3, Decoder_0_out_4, Decoder_0_out_5, Decoder_0_out_6, Decoder_0_out_7, and_6_out, and_5_out, and_4_out, and_3_out, and_2_out, and_0_out, and_1_out;
  wire [7:0] \8bit-register_7_out , Multiplexer_1_out, Multiplexer_0_out, \8bit-register_6_out , \8bit-register_5_out , \8bit-register_4_out , \8bit-register_3_out , \8bit-register_2_out , \8bit-register_1_out , \8bit-register_0_out , const_0;
  \8bit-register  \8bit-register_7 (\8bit-register_7_out , rd_data, and_6_out, clock, reset);
  Multiplexer8 #(8) Multiplexer_1(Multiplexer_1_out, const_0, \8bit-register_1_out , \8bit-register_2_out , \8bit-register_3_out , \8bit-register_4_out , \8bit-register_5_out , \8bit-register_6_out , \8bit-register_7_out , rs2[2:0]);
  assign rs2_data = Multiplexer_1_out;
  Multiplexer8 #(8) Multiplexer_0(Multiplexer_0_out, const_0, \8bit-register_1_out , \8bit-register_2_out , \8bit-register_3_out , \8bit-register_4_out , \8bit-register_5_out , \8bit-register_6_out , \8bit-register_7_out , rs1[2:0]);
  assign rs1_data = Multiplexer_0_out;
  \8bit-register  \8bit-register_6 (\8bit-register_6_out , rd_data, and_5_out, clock, reset);
  \8bit-register  \8bit-register_5 (\8bit-register_5_out , rd_data, and_4_out, clock, reset);
  \8bit-register  \8bit-register_4 (\8bit-register_4_out , rd_data, and_3_out, clock, reset);
  \8bit-register  \8bit-register_3 (\8bit-register_3_out , rd_data, and_2_out, clock, reset);
  \8bit-register  \8bit-register_2 (\8bit-register_2_out , rd_data, and_0_out, clock, reset);
  \8bit-register  \8bit-register_1 (\8bit-register_1_out , rd_data, and_1_out, clock, reset);
  \8bit-register  \8bit-register_0 (\8bit-register_0_out , rd_data, , clock, reset);
  
  Decoder8 #(3) Decoder_0(Decoder_0_out_0, Decoder_0_out_1, Decoder_0_out_2, Decoder_0_out_3, Decoder_0_out_4, Decoder_0_out_5, Decoder_0_out_6, Decoder_0_out_7, rd[2:0]);
  assign and_6_out = Decoder_0_out_7 & RegWrite;
  assign and_5_out = Decoder_0_out_6 & RegWrite;
  assign and_4_out = Decoder_0_out_5 & RegWrite;
  assign and_3_out = Decoder_0_out_4 & RegWrite;
  assign and_2_out = Decoder_0_out_3 & RegWrite;
  assign and_0_out = Decoder_0_out_2 & RegWrite;
  assign and_1_out = Decoder_0_out_1 & RegWrite;
  
  
  assign const_0 = 8'b00000000;
  assign Decoder_0_out_0 = 1'b0;
endmodule

module \r-type (\R-type , codop);
  output \R-type ;
  input [6:0] codop;
  wire not_2_out, and_0_out, not_1_out, not_0_out;
  
  assign not_2_out = ~codop[6];
  assign and_0_out = not_0_out & codop[1] & codop[0] & not_1_out & codop[4] & codop[5] & not_2_out;
  assign \R-type  = and_0_out;
  assign not_1_out = ~codop[3];
  assign not_0_out = ~codop[2];
endmodule

module load(load, codop);
  output load;
  input [6:0] codop;
  wire not_4_out, and_0_out, not_3_out, not_2_out, not_1_out, not_0_out;
  
  assign not_4_out = ~codop[6];
  assign and_0_out = not_0_out & codop[1] & codop[0] & not_1_out & not_2_out & not_3_out & not_4_out;
  assign load = and_0_out;
  assign not_3_out = ~codop[5];
  assign not_2_out = ~codop[4];
  assign not_1_out = ~codop[3];
  assign not_0_out = ~codop[2];
endmodule

module store(store, codop);
  output store;
  input [6:0] codop;
  wire not_3_out, and_0_out, not_2_out, not_1_out, not_0_out;
  
  assign not_3_out = ~codop[6];
  assign and_0_out = not_0_out & codop[1] & codop[0] & not_1_out & not_2_out & codop[5] & not_3_out;
  assign store = and_0_out;
  assign not_2_out = ~codop[4];
  assign not_1_out = ~codop[3];
  assign not_0_out = ~codop[2];
endmodule

module branch(branch, codop);
  output branch;
  input [6:0] codop;
  wire and_0_out, not_2_out, not_1_out, not_0_out;
  
  assign and_0_out = not_0_out & codop[1] & codop[0] & not_1_out & not_2_out & codop[5] & codop[6];
  assign branch = and_0_out;
  assign not_2_out = ~codop[4];
  assign not_1_out = ~codop[3];
  assign not_0_out = ~codop[2];
endmodule






module control_unit(Branch, ALUOp, ALUSrc, MemtoReg, RegWrite, MemRead, MemWrite, instruction);
  output Branch,  ALUSrc,  MemtoReg,  RegWrite,  MemRead,  MemWrite;
  output [1:0] ALUOp;
  input [6:0] instruction;
  wire branch_3_out, \r-type_0_out , or_1_out, load_1_out, or_0_out, store_2_out;
  wire [1:0] Splitter_0_cmb;
  branch branch_3(branch_3_out, instruction);
  assign Splitter_0_cmb = {\r-type_0_out ,branch_3_out};
  assign ALUOp = Splitter_0_cmb;
  assign Branch = branch_3_out;
  \r-type  \r-type_0 (\r-type_0_out , instruction);
  assign or_1_out = \r-type_0_out  | load_1_out;
  assign RegWrite = or_1_out;
  load load_1(load_1_out, instruction);
  assign MemRead = load_1_out;
  assign MemtoReg = load_1_out;
  assign or_0_out = store_2_out | load_1_out;
  assign ALUSrc = or_0_out;
  store store_2(store_2_out, instruction);
  assign MemWrite = store_2_out;
endmodule





module ALU_8bit(Overflow, Result, Zero, ALU_operation, b, a);
  output Overflow,  Zero;
  output [7:0] Result;
  input [3:0] ALU_operation;
  input [7:0] b, a;
  wire ALU_1bit_v2_3_out_0, ALU_1bit_v2_3_out_1, ALU_1bit_v2_3_out_2, ALU_1bit_v1_0_out_0, ALU_1bit_v1_0_out_1, ALU_1bit_v1_1_out_0, ALU_1bit_v1_1_out_1, ALU_1bit_v1_2_out_0, ALU_1bit_v1_2_out_1, ALU_1bit_v1_4_out_0, ALU_1bit_v1_4_out_1, ALU_1bit_v1_5_out_0, ALU_1bit_v1_5_out_1, ALU_1bit_v1_6_out_0, ALU_1bit_v1_6_out_1, ALU_1bit_v1_7_out_0, ALU_1bit_v1_7_out_1, nor_0_out, Ground_6_out, Ground_5_out, Ground_4_out, Ground_3_out, Ground_2_out, Ground_1_out, Ground_0_out;
  wire [7:0] Splitter_3_cmb;
  
  ALU_1bit_v2 ALU_1bit_v2_3(ALU_1bit_v2_3_out_0, ALU_1bit_v2_3_out_1, ALU_1bit_v2_3_out_2, a[7], b[7], ALU_1bit_v1_7_out_1, ALU_operation[1:0], Ground_6_out, ALU_operation[3], ALU_operation[2]);
  
      always @ (*)
        $display("DigitalLed:ALU_1bit_v2_3_out_2=%d", ALU_1bit_v2_3_out_2);
  assign Overflow = ALU_1bit_v2_3_out_2;
  ALU_1bit_v1 ALU_1bit_v1_0(ALU_1bit_v1_0_out_0, ALU_1bit_v1_0_out_1, a[0], b[0], ALU_operation[2], ALU_operation[1:0], ALU_1bit_v2_3_out_1, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_1(ALU_1bit_v1_1_out_0, ALU_1bit_v1_1_out_1, a[1], b[1], ALU_1bit_v1_0_out_1, ALU_operation[1:0], Ground_0_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_2(ALU_1bit_v1_2_out_0, ALU_1bit_v1_2_out_1, a[2], b[2], ALU_1bit_v1_1_out_1, ALU_operation[1:0], Ground_1_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_4(ALU_1bit_v1_4_out_0, ALU_1bit_v1_4_out_1, a[3], b[3], ALU_1bit_v1_2_out_1, ALU_operation[1:0], Ground_2_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_5(ALU_1bit_v1_5_out_0, ALU_1bit_v1_5_out_1, a[4], b[4], ALU_1bit_v1_4_out_1, ALU_operation[1:0], Ground_3_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_6(ALU_1bit_v1_6_out_0, ALU_1bit_v1_6_out_1, a[5], b[5], ALU_1bit_v1_5_out_1, ALU_operation[1:0], Ground_4_out, ALU_operation[3], ALU_operation[2]);
  ALU_1bit_v1 ALU_1bit_v1_7(ALU_1bit_v1_7_out_0, ALU_1bit_v1_7_out_1, a[6], b[6], ALU_1bit_v1_6_out_1, ALU_operation[1:0], Ground_5_out, ALU_operation[3], ALU_operation[2]);
  assign Splitter_3_cmb = {ALU_1bit_v2_3_out_0,ALU_1bit_v1_7_out_0,ALU_1bit_v1_6_out_0,ALU_1bit_v1_5_out_0,ALU_1bit_v1_4_out_0,ALU_1bit_v1_2_out_0,ALU_1bit_v1_1_out_0,ALU_1bit_v1_0_out_0};
  assign Result = Splitter_3_cmb;
  
  assign nor_0_out = ~(Splitter_3_cmb[3] | Splitter_3_cmb[2] | Splitter_3_cmb[1] | Splitter_3_cmb[0] | Splitter_3_cmb[4] | Splitter_3_cmb[5] | Splitter_3_cmb[6] | Splitter_3_cmb[7]);
  assign Zero = nor_0_out;
  
      always @ (*)
        $display("DigitalLed:nor_0_out=%d", nor_0_out);
  
  
  
  assign Ground_6_out = 1'b0;
  assign Ground_5_out = 1'b0;
  assign Ground_4_out = 1'b0;
  assign Ground_3_out = 1'b0;
  assign Ground_2_out = 1'b0;
  assign Ground_1_out = 1'b0;
  assign Ground_0_out = 1'b0;
endmodule

module ALU_control(operation, ALUOp, instruction);
  output [3:0] operation;
  input [1:0] ALUOp;
  input [31:0] instruction;
  wire and_1_out, or_1_out, not_1_out, or_0_out, and_2_out, not_3_out, not_0_out, not_2_out, and_0_out;
  wire [3:0] Splitter_1_cmb;
  
  assign and_1_out = ALUOp[1] & instruction[30];
  assign or_1_out = ALUOp[0] | and_1_out;
  assign Splitter_1_cmb = {and_0_out,or_1_out,or_0_out,and_2_out};
  assign operation = Splitter_1_cmb;
  assign not_1_out = ~instruction[14];
  assign or_0_out = not_0_out | not_1_out;
  assign and_2_out = ALUOp[1] & instruction[13] & not_3_out;
  assign not_3_out = ~instruction[12];
  
  assign not_0_out = ~ALUOp[1];
  assign not_2_out = ~ALUOp[0];
  assign and_0_out = ALUOp[0] & not_2_out;
endmodule




module imm_gen(immediate, instruction);
  output [7:0] immediate;
  input [31:0] instruction;
  wire branch_2_out, PriorityEncoder_0_out_0, PriorityEncoder_0_out_1, store_1_out, load_0_out, Ground_2_out, Ground_1_out;
  wire [1:0] Splitter_7_cmb;
  wire [11:0] Multiplexer_0_out, Splitter_5_cmb, Splitter_8_cmb, Splitter_3_cmb, Ground_0_out;
  
  branch branch_2(branch_2_out, instruction[6:0]);
  PriorityEncoder4 #(2) PriorityEncoder_0(PriorityEncoder_0_out_0, PriorityEncoder_0_out_1, , load_0_out, store_1_out, branch_2_out, Ground_1_out);
  assign Splitter_7_cmb = {PriorityEncoder_0_out_1,PriorityEncoder_0_out_0};
  Multiplexer4 #(12) Multiplexer_0(Multiplexer_0_out, instruction[31:20], Splitter_3_cmb, Splitter_8_cmb, Ground_0_out, Splitter_7_cmb);
  
  assign immediate = Multiplexer_0_out[7:0];
  store store_1(store_1_out, instruction[6:0]);
  load load_0(load_0_out, instruction[6:0]);
  
  
  assign Splitter_5_cmb = {instruction[31],instruction[7],instruction[30:25],instruction[11:8]};
  
  assign Splitter_8_cmb = {Splitter_5_cmb[10:0],Ground_2_out};
  
  assign Splitter_3_cmb = {instruction[31:25],instruction[11:7]};
  assign Ground_2_out = 1'b0;
  assign Ground_1_out = 1'b0;
  assign Ground_0_out = 12'b0;
endmodule


